name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      INPUT:
        description: "The terraform apply will run if you say YES"
        required: true
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Setting the input variables
      run: |
        Add-Content -Path $env:GITHUB_ENV -Value "InputValue=${{github.event.inputs.INPUT}}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI to initialize
      run: gcloud init
    
    - name: authentication
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        # gcloud auth login --console-only

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 1.0.2 # must be same version as main.tf
        terraform_wrapper: false
    
    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: env.InputValue == 'Yes'
      run:  terraform plan -auto-approve
        
