name: Terraform Plan

on:
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI to initialize
      run: gcloud init
    
    - name: authentication
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        # gcloud auth login --console-only

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 1.0.2 # must be same version as main.tf
        terraform_wrapper: false
    
    - name: Terraform Formatting
      id: fmt
      working-directory: ./
      continue-on-error: false
      run: terraform fmt -recursive

    - name: Initialize terraform
      run: terraform init -input=false

    - name: Terraform plan
      continue-on-error: false
      run: |
        mkdir -pv /home/runner/terraform/plans && outfile="${GITHUB_JOB}_${GITHUB_RUN_NUMBER}_`date +%Y_%m_%d_%I_%M_%p`.tf_plan_out"
        terraform plan -input=false -refresh=true  -out=/home/runner/terraform/plans/terraform_plan.out
        echo "SHA256 for this modification:" &&  terraform show /home/runner/terraform/plans/terraform_plan.out | sha256sum  | awk '{ print $1 }'
